name: build-latex

on:
  push:
    paths:
      - '.github/workflows/build_latex.yml'
      - 'praca/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: praca
          root_file: mgr.tex

      - name: Commit
        uses: dfm/force-push-branch-action@v1
        with:
          target-branch: pdf
          commit-message: "GitHub Action: Update mgr.pdf"
          path: praca/mgr.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: mgr
          path: praca/mgr.pdf

  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: count
        run: |
          sudo apt install texlive-extra-utils
          texcount -total praca/mgr.tex
          echo "##[set-output name=count;]$(texcount -total praca/mgr.tex | awk '/Words in text/ {print $4}')"

      - name: Word count badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: count
          LABEL: 'PDF word count'
          ICON: 'github'
          STATUS: ${{ steps.count.outputs.count }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
