name: build-elm
on:
  push:
    paths:
    - 'src/**'
    - 'assets/**'
    - '**.html'
    - '**.js'

jobs:
  build_elm:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Build Elm application
      uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1
    - run: elm make src/Main.elm --output=assets/main.js

    - name: Deploy to Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages


