name: build-latex
on:
  push:
    paths:
      - '.github/workflows/build_latex.yml'
      - 'praca/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: praca
          root_file: mgr.tex

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Update mgr.pdf"
          branch: ${{ github.ref }}

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: mgr
          path: praca/mgr.pdf
  badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: count
        run: |
          sudo apt install texlive-extra-utils
          echo "##[set-output name=count;]$(texcount -sum praca/mgr.tex | awk '/Sum/ {print $3}')"

      - name: Word count badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: count
          LABEL: 'PDF word count'
          ICON: 'github'
          STATUS: ${{ steps.count.outputs.count }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
