name: build-elm
on:
  push:
    paths:
    - '.github/workflows/build_elm.yml'
    - 'elm/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Elm
      uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1

    - name: Build
      working-directory: elm
      run: elm make src/Main.elm --output=assets/main.js --optimize

    - name: Upload main.js
      uses: actions/upload-artifact@v2
      with:
        name: main.js
        path: elm/assets/main.js

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./elm

    - uses: actions/download-artifact@v3
      with:
        name: main.js
        path: assets/

    - uses: EndBug/add-and-commit@v9
      with:
        add: 'assets/main.js --force'
        new_branch: gh-pages

