name: build-elm
on:
  push:
    paths:
    - '.github/workflows/build_elm.yml'
    - 'src/**'
    - 'assets/**'
    - '**.html'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1
    - run: elm make src/Main.elm --output=assets/main.js --optimize

    - name: Auto Minify
      uses: dolfies/auto-minify@v1
      with:
        files: "assets/main.js"
        overwrite: true

    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Update assets/main.js"
        branch: ${{ github.ref }}
