name: Build Elm application
on: [push]
defaults:
  run:
    working-directory: /
jobs:
  build_elm:
    runs-on: ubuntu-latest
    steps:
    - uses: jorelali/setup-elm@v3
      with:
        elm-version: 0.19.1
    - run: pwd | ls | elm make src/Main.elm 
