name: build-latex
on:
  push:
    paths:
      - '.github/workflows/build_latex.yml'
      - 'praca/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: praca
          root_file: mgr.tex

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Update mgr.pdf"
          branch: ${{ github.ref }}
        continue-on-error: true

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: mgr
          path: praca/mgr.pdf
