name: texcount_badge.yml
on:
  push:
    paths:
      - '.github/workflows/texcount_badge.yml'
      - 'praca/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - id: count
        run: |
          apt install texlive-extra-utils
          echo "##[set-output name=count;]$(texcount -sum mgr.tex | awk '/Sum/ {print $3}')"
        
      - name: Word count badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: count
          LABEL: 'Word count'
          ICON: 'github'
          STATUS: ${{ steps.count.outputs.count }}
          COLOR: blue
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
